baseURL = "https://rodbalbino.github.io/"
languageCode = "pt-br"
title = "balbino dev"

publishDir = "docs"


[params]
  twitter = "https://twitter.com/B4L31N0"
  github = "https://github.com/rodbalbino/"

  iconOrder = ["Twitter", "GitHub"]


[[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "Posts"
    url = "/post"

[[menu.main]]
    identifier = "home"
    name = "home"
    title = "Home"
    url = "/"
